"""
Prompt Validation Layer

Validates Phi3-generated prompts to ensure they follow ontology constraints
and don't introduce hallucinations.
"""

from typing import Dict, List, Any, Tuple
import re


class PromptValidator:
    """Validates and enhances Phi3-generated prompts."""

    def __init__(self, context: Dict[str, Any]):
        """
        Initialize validator with ontology context.

        Args:
            context: Ontology context used to generate the prompt
        """
        self.context = context
        self.allowed_dependencies = self._extract_allowed_dependencies()

    def _extract_allowed_dependencies(self) -> set:
        """Extract set of allowed dependency names from context."""
        allowed = set()

        # Constructor dependencies
        constructor_deps = self.context.get('constructor_dependencies', [])
        allowed.update(constructor_deps)

        # Categorized dependencies
        categorized = self.context.get('categorized_dependencies', {})
        for category in ['repositories', 'services', 'others']:
            for dep in categorized.get(category, []):
                dep_name = dep.get('dependency_name', '')
                if dep_name:
                    allowed.add(dep_name)

        return allowed

    def validate(self, generated_prompt: str) -> Tuple[bool, List[str], List[str]]:
        """
        Validate the generated prompt.

        Args:
            generated_prompt: The prompt generated by Phi3

        Returns:
            Tuple of (is_valid, errors, warnings)
        """
        errors = []
        warnings = []

        # Check 1: Dependency verification
        dep_errors, dep_warnings = self._validate_dependencies(generated_prompt)
        errors.extend(dep_errors)
        warnings.extend(dep_warnings)

        # Check 2: Architecture pattern verification
        arch_warnings = self._validate_architecture(generated_prompt)
        warnings.extend(arch_warnings)

        # Check 3: Anti-hallucination checks
        hallucination_errors = self._check_hallucinations(generated_prompt)
        errors.extend(hallucination_errors)

        # Check 4: Completeness checks
        completeness_warnings = self._check_completeness(generated_prompt)
        warnings.extend(completeness_warnings)

        is_valid = len(errors) == 0

        return is_valid, errors, warnings

    def _validate_dependencies(self, prompt: str) -> Tuple[List[str], List[str]]:
        """Validate that only allowed dependencies are referenced."""
        errors = []
        warnings = []

        if not self.allowed_dependencies:
            warnings.append("No dependencies found in ontology - cannot validate dependency usage")
            return errors, warnings

        # Common patterns for dependency references
        # Examples: "this.userRepository", "await userService.findById", "inject UserRepository"
        dependency_patterns = [
            r'this\.(\w+)',  # this.serviceName
            r'await\s+(\w+)\.',  # await serviceName.
            r'inject\s+(\w+)',  # inject ServiceName
            r'constructor\([^)]*\b(\w+Repository|\w+Service)\b',  # constructor params
        ]

        referenced_deps = set()
        for pattern in dependency_patterns:
            matches = re.findall(pattern, prompt, re.IGNORECASE)
            referenced_deps.update(matches)

        # Check if referenced dependencies are in allowed list
        # This is a soft check - we look for exact matches or partial matches
        for ref_dep in referenced_deps:
            # Check for exact match or if ref_dep is contained in any allowed dependency
            found = False
            for allowed in self.allowed_dependencies:
                if ref_dep.lower() in allowed.lower() or allowed.lower() in ref_dep.lower():
                    found = True
                    break

            if not found:
                # This is a warning, not an error, because the LLM might use different naming
                warnings.append(f"Potentially invented dependency: '{ref_dep}' not found in ontology")

        return errors, warnings

    def _validate_architecture(self, prompt: str) -> List[str]:
        """Validate architecture pattern adherence."""
        warnings = []

        tech_stack = self.context.get('tech_stack', '')
        component_type = self.context.get('component', {}).get('type', '')

        # Check for architecture violations based on tech stack
        if 'backend' in tech_stack.lower() or 'nestjs' in tech_stack.lower():
            # Check for direct database access in services
            if 'service' in component_type.lower():
                db_patterns = [
                    r'new\s+\w+Connection',
                    r'createConnection\(',
                    r'getConnection\(',
                    r'execute\s*\(',
                ]
                for pattern in db_patterns:
                    if re.search(pattern, prompt, re.IGNORECASE):
                        warnings.append(
                            f"Potential architecture violation: Service may be accessing database directly. "
                            f"Should use Repository layer."
                        )
                        break

            # Check for business logic in controllers
            if 'controller' in component_type.lower():
                business_logic_indicators = [
                    r'for\s*\(',
                    r'while\s*\(',
                    r'if\s*\([^)]{50,}\)',  # Complex conditionals
                ]
                complexity_count = sum(
                    len(re.findall(pattern, prompt, re.IGNORECASE))
                    for pattern in business_logic_indicators
                )
                if complexity_count > 3:
                    warnings.append(
                        "Potential architecture violation: Controller may contain business logic. "
                        "Business logic should be in Service layer."
                    )

        return warnings

    def _check_hallucinations(self, prompt: str) -> List[str]:
        """Check for common hallucination patterns."""
        errors = []

        # Check 1: Invented method calls
        # Look for method calls that seem invented (common patterns AI tends to hallucinate)
        hallucinated_methods = [
            r'findByEmail\(',  # Common but might not exist
            r'findByUsername\(',
            r'deleteAll\(',
            r'updateAll\(',
        ]

        # Only flag if not in context
        component = self.context.get('component', {})
        methods = component.get('methods', [])
        method_names = [m.get('name', '') for m in methods] if methods else []

        for pattern in hallucinated_methods:
            if re.search(pattern, prompt):
                method_name = pattern.replace('(', '').replace('\\', '')
                if method_name not in method_names:
                    # This is a warning since the method might exist but not be in ontology
                    errors.append(
                        f"Potentially invented method: '{method_name}' not found in component methods"
                    )

        return errors

    def _check_completeness(self, prompt: str) -> List[str]:
        """Check if prompt is complete and comprehensive."""
        warnings = []

        # Check for minimum content
        if len(prompt) < 500:
            warnings.append("Generated prompt seems too short - may be incomplete")

        # Check for key sections
        required_sections = [
            ('TASK', 'Task definition'),
            ('ONTOLOGY', 'Ontology constraints'),
            ('DEPENDENCIES', 'Dependency information'),
        ]

        for keyword, section_name in required_sections:
            if keyword.upper() not in prompt.upper():
                warnings.append(f"Missing expected section: {section_name}")

        return warnings

    def enhance_prompt(self, generated_prompt: str) -> str:
        """
        Enhance the generated prompt with safety guardrails.

        Args:
            generated_prompt: The prompt generated by Phi3

        Returns:
            Enhanced prompt with additional safety constraints
        """
        # Add ontology enforcement header
        header = self._build_enforcement_header()

        # Add validation footer
        footer = self._build_validation_footer()

        # Combine
        enhanced = f"{header}\n\n{generated_prompt}\n\n{footer}"

        return enhanced

    def _build_enforcement_header(self) -> str:
        """Build strict enforcement header."""
        deps_list = "\n".join([f"  ✅ {dep}" for dep in sorted(self.allowed_dependencies)])

        if not deps_list:
            deps_list = "  ⚠️ No dependencies found in ontology"

        return f"""{'='*70}
🔒 ONTOLOGY ENFORCEMENT (CRITICAL - READ FIRST)
{'='*70}

BEFORE proceeding, you MUST understand these ABSOLUTE constraints:

**ALLOWED DEPENDENCIES (ONLY THESE):**
{deps_list}

❌ DO NOT use any service, repository, or dependency NOT listed above
❌ DO NOT invent methods that don't exist in the ontology
❌ DO NOT violate the architecture pattern specified below

If you need functionality not available in the ontology:
- STATE clearly what is missing
- EXPLAIN why it's needed
- DO NOT implement it yourself

{'='*70}"""

    def _build_validation_footer(self) -> str:
        """Build validation checklist footer."""
        return f"""{'='*70}
✅ VALIDATION CHECKLIST
{'='*70}

Before submitting your code, verify:

1. ✅ ONLY used dependencies listed in "ALLOWED DEPENDENCIES"
2. ✅ ONLY called methods that exist in the ontology
3. ✅ FOLLOWED the architecture pattern (Controller→Service→Repository)
4. ✅ NO business logic in Controllers
5. ✅ NO direct database access from Services
6. ✅ Proper error handling implemented
7. ✅ Type safety maintained
8. ✅ Input validation added

If ANY check fails, STOP and revise your code.

{'='*70}"""

    def get_validation_summary(
        self,
        is_valid: bool,
        errors: List[str],
        warnings: List[str]
    ) -> Dict[str, Any]:
        """
        Get validation summary.

        Args:
            is_valid: Whether prompt passed validation
            errors: List of errors found
            warnings: List of warnings found

        Returns:
            Validation summary dictionary
        """
        return {
            'is_valid': is_valid,
            'errors': errors,
            'warnings': warnings,
            'error_count': len(errors),
            'warning_count': len(warnings),
            'allowed_dependencies': list(self.allowed_dependencies),
            'recommendation': 'APPROVED' if is_valid else 'NEEDS_REVIEW'
        }
